import type { DatabaseSchema } from '@figma-codegen/spec-gen';
import type { GeneratedFile } from './entity-generator.js';

/**
 * DB Schema에서 Flyway 마이그레이션 SQL 스크립트를 생성합니다.
 */
export class JavaMigrationGenerator {
    generate(dbSchema: DatabaseSchema): GeneratedFile {
        return {
            fileName: 'V1__init_schema.sql',
            path: 'V1__init_schema.sql',
            content: `-- Flyway Migration V1: Initial Schema
-- Auto-generated by figma-codegen

${dbSchema.sql}
`,
        };
    }
}
